#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(Sensor, in1,    Gyro,           sensorGyro)
#pragma config(Sensor, in2,    DR4Bpot,        sensorPotentiometer)
#pragma config(Sensor, in3,    CBpot,          sensorPotentiometer)
#pragma config(Sensor, dgtl1,  RDenc,          sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  LDenc,          sensorQuadEncoder)
#pragma config(Motor,  port2,           RD1,           tmotorVex393HighSpeed_MC29, openLoop, encoderPort, dgtl1)
#pragma config(Motor,  port3,           RD2,           tmotorVex393HighSpeed_MC29, openLoop, encoderPort, dgtl1)
#pragma config(Motor,  port4,           MG,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           Roller,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           CB,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           DR4B,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           LD2,           tmotorVex393HighSpeed_MC29, openLoop, encoderPort, dgtl3)
#pragma config(Motor,  port9,           LD1,           tmotorVex393HighSpeed_MC29, openLoop, encoderPort, dgtl3)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"


//--------------------------------------------// Reset Sensor Voids

void resetSensors()
{
	SensorValue[RDenc] = 0;
	SensorValue[LDenc] = 0;
	SensorValue[Gyro] = 0;
}

//--------------------------------------------//


//--------------------------------------------// Sensor Drive Voids

void driveForwards(int power, int sensoramount)
{
	while (SensorValue[RDenc] < sensoramount || SensorValue[LDenc] < sensoramount)
	{
		if (SensorValue[RDenc] < sensoramount)
		{
			motor[RD1] = power;
			motor[RD2] = power;
		}
		else
		{
			motor[RD1] = 0;
			motor[RD2] = 0;
		}
		if (SensorValue[LDenc] < sensoramount)
		{
			motor[LD1] = power;
			motor[LD2] = power;
		}
		else
		{
			motor[LD1] = 0;
			motor[LD2] = 0;
		}
	}
	motor[RD1] = 0;
	motor[RD2] = 0;
	motor[LD1] = 0;
	motor[LD2] = 0;
}

void driveBackwards(int power, int sensoramount)
{
	while (SensorValue[RDenc] > -sensoramount || SensorValue[LDenc] > -sensoramount)
	{
		if (SensorValue[RDenc] > -sensoramount)
		{
			motor[RD1] = -power;
			motor[RD2] = -power;
		}
		else
		{
			motor[RD1] = 0;
			motor[RD2] = 0;
		}
		if (SensorValue[LDenc] > -sensoramount)
		{
			motor[LD1] = -power;
			motor[LD2] = -power;
		}
		else
		{
			motor[LD1] = 0;
			motor[LD2] = 0;
		}
	}
	motor[RD1] = 0;
	motor[RD2] = 0;
	motor[LD1] = 0;
	motor[LD2] = 0;
}

//--------------------------------------------//


//--------------------------------------------// Turn Encoder Voids

void turnLeftenc(int power, int sensoramount)
{
	while (SensorValue[RDenc] < sensoramount || SensorValue[LDenc] > -sensoramount)
	{
		if (SensorValue[RDenc] < sensoramount)
		{
			motor[RD1] = power;
			motor[RD2] = power;
		}
		else
		{
			motor[RD1] = 0;
			motor[RD2] = 0;
		}
		if (SensorValue[LDenc] > -sensoramount)
		{
			motor[LD1] = -power;
			motor[LD2] = -power;
		}
		else
		{
			motor[LD1] = 0;
			motor[LD2] = 0;
		}
	}
	motor[RD1] = 0;
	motor[RD2] = 0;
	motor[LD1] = 0;
	motor[LD2] = 0;
}

void turnRightenc(int power, int sensoramount)
{
	while (SensorValue[RDenc] > -sensoramount || SensorValue[LDenc] < sensoramount)
	{
		if (SensorValue[RDenc] > -sensoramount)
		{
			motor[RD1] = -power;
			motor[RD2] = -power;
		}
		else
		{
			motor[RD1] = 0;
			motor[RD2] = 0;
		}
		if (SensorValue[LDenc] < sensoramount)
		{
			motor[LD1] = power;
			motor[LD2] = power;
		}
		else
		{
			motor[LD1] = 0;
			motor[LD2] = 0;
		}
	}
	motor[RD1] = 0;
	motor[RD2] = 0;
	motor[LD1] = 0;
	motor[LD2] = 0;
}

//--------------------------------------------//


//--------------------------------------------// Turn Gyro Voids

void turnLeft (int power, int angle)
{
	angle = angle*10;
	while (abs(SensorValue[Gyro]) < angle)
	{
		motor[RD1] = power;
		motor[RD2] = power;
		motor[LD1] = -power;
		motor[LD2] = -power;
	}
	motor[RD1] = 0;
	motor[RD2] = 0;
	motor[LD1] = 0;
	motor[LD2] = 0;
}

void turnRight (int power, int angle)
{
	angle = angle*10;
	while (abs(SensorValue[Gyro]) < angle)
	{
		motor[RD1] = -power;
		motor[RD2] = -power;
		motor[LD1] = power;
		motor[LD2] = power;
	}
	motor[RD1] = 0;
	motor[RD2] = 0;
	motor[LD1] = 0;
	motor[LD2] = 0;
}

//--------------------------------------------//


//--------------------------------------------// Special Voids

void specialBack(int power1, int power2, int sensoramount1, int sensoramount2)
{
	while (SensorValue[RDenc] > -sensoramount1 || SensorValue[LDenc] > -sensoramount2)
	{
		if (SensorValue[RDenc] > -sensoramount1)
		{
			motor[RD1] = -power1;
			motor[RD2] = -power1;
		}
		else
		{
			motor[RD1] = 0;
			motor[RD2] = 0;
		}
		if (SensorValue[LDenc] < -sensoramount2)
		{
			motor[LD1] = -power2;
			motor[LD2] = -power2;
		}
		else
		{
			motor[LD1] = 0;
			motor[LD2] = 0;
		}
	}
	motor[RD1] = 0;
	motor[RD2] = 0;
	motor[LD1] = 0;
	motor[LD2] = 0;
}

//--------------------------------------------//


//--------------------------------------------// Time Drive Voids

void timeForwards(int power, int time)
{
	motor[RD1] = power;
	motor[RD2] = power;
	motor[LD1] = power;
	motor[LD2] = power;
	wait1Msec(time);
	motor[RD1] = 0;
	motor[RD2] = 0;
	motor[LD1] = 0;
	motor[LD2] = 0;
}

void timeBackwards(int power, int time)
{
	motor[RD1] = -power;
	motor[RD2] = -power;
	motor[LD1] = -power;
	motor[LD2] = -power;
	wait1Msec(time);
	motor[RD1] = 0;
	motor[RD2] = 0;
	motor[LD1] = 0;
	motor[LD2] = 0;
}

//--------------------------------------------//


//--------------------------------------------// Time Turn Voids

void timeTurnLeft(int power, int time)
{
	motor[RD1] = power;
	motor[RD2] = power;
	motor[LD1] = -power;
	motor[LD2] = -power;
	wait1Msec(time);
	motor[RD1] = 0;
	motor[RD2] = 0;
	motor[LD1] = 0;
	motor[LD2] = 0;
}

void timeTurnRight(int power, int time)
{
	motor[RD1] = -power;
	motor[RD2] = -power;
	motor[LD1] = power;
	motor[LD2] = power;
	wait1Msec(time);
	motor[RD1] = 0;
	motor[RD2] = 0;
	motor[LD1] = 0;
	motor[LD2] = 0;
}

//--------------------------------------------//


//--------------------------------------------// Time Side Voids

void timeLeftSide(int power, int time)
{
	motor[LD1] = power;
	motor[LD2] = power;
	wait1Msec(time);
	motor[LD1] = 0;
	motor[LD2] = 0;
}

void timeRightSide(int power, int time)
{
	motor[LD1] = power;
	motor[LD2] = power;
	wait1Msec(time);
	motor[LD1] = 0;
	motor[LD2] = 0;
}

//--------------------------------------------//


//--------------------------------------------// Mobile Goal Voids

void liftMobileGoal(int power, int time)
{
	motor[MG] = power;
	wait1Msec(time);
	motor[MG] = 0;
}

void lowerMobileGoal(int power, int time)
{
	motor[MG] = -power;
	wait1Msec(time);
	motor[MG] = 0;
}

//--------------------------------------------//


//--------------------------------------------// DR4B Sensor Voids

void liftDR4B(int power, int sensoramount)
{
	while(SensorValue[DR4Bpot] < sensoramount)
	{
		motor[DR4B] = power;
	}
	motor[DR4B] = 0;
}

void lowerDR4B(int power, int sensoramount)
{
	while(SensorValue[DR4Bpot] > sensoramount)
	{
		motor[DR4B] = -power;
	}
	motor[DR4B] = 0;
}

//--------------------------------------------//


//--------------------------------------------// DR4B Time Voids

void timeLiftDR4B(int power, int time)
{
	motor[DR4B] = power;
	wait1Msec(time);
	motor[DR4B] = 0;
}

void timeLowerDR4B(int power, int time)
{
	motor[DR4B] = -power;
	wait1Msec(time);
	motor[DR4B] = 0;
}

//--------------------------------------------//


//--------------------------------------------// Chain Bar Sensor Voids

void liftChainBar(int power, int sensoramount)
{
	while(SensorValue[CBpot] < sensoramount)
	{
		motor[CB] = power;
	}
	motor[CB] = 0;
}

void lowerChainBar(int power, int sensoramount)
{
	while(SensorValue[CBpot] > sensoramount)
	{
		motor[CB] = -power;
	}
	motor[CB] = 0;
}

//--------------------------------------------//


//--------------------------------------------// Chain Bar Time Voids

void timeLiftChainBar(int power, int time)
{
	motor[CB] = power;
	wait1Msec(time);
	motor[CB] = 0;
}

void timeLowerChainBar(int power, int time)
{
	motor[CB] = -power;
	wait1Msec(time);
	motor[CB] = 0;
}

//--------------------------------------------//


//--------------------------------------------// Cone Voids

void grabCone(int power, int time)
{
	motor[Roller] = -power;
	wait1Msec(time);
	motor[Roller] = 0;
}

void releaseCone(int power, int time)
{
	motor[Roller] = power;
	wait1Msec(time);
	motor[Roller] = 0;
}

//--------------------------------------------//


//--------------------------------------------// LCD Voids

int autonomousMode = 1;

void clearLCD()
{
	clearLCDLine(0);
	clearLCDLine(1);
}

void autonomousSelection() //Void for Auton Selection
{
	clearLCD();
	bLCDBacklight = true;
	while (nLCDButtons != 2)
	{
		if (nLCDButtons == 1)
		{
			autonomousMode--;
			while(nLCDButtons == 1) {wait1Msec(10);}
		}
		if (nLCDButtons == 4)
		{
			autonomousMode++;
			while(nLCDButtons == 4) {wait1Msec(10);}
		}
		if (autonomousMode == 1) //Display Auton Name
		{
			clearLCD();
			displayLCDCenteredString(0,"Left 26");
			displayLCDCenteredString(1,"<<   Enter   >>");
		}
		else	if (autonomousMode == 2) //Display Auton Name
		{
			clearLCD();
			displayLCDCenteredString(0,"Right 26");
			displayLCDCenteredString(1,"<<   Enter   >>");
		}
		else if (autonomousMode == 3) //Display Auton Name
		{
			clearLCD();
			displayLCDCenteredString(0,"Left 18");
			displayLCDCenteredString(1,"<<   Enter   >>");
		}
		else if (autonomousMode == 4) //Display Auton Name
		{
			clearLCD();
			displayLCDCenteredString(0,"Right 18");
			displayLCDCenteredString(1,"<<   Enter   >>");
		}
		else if (autonomousMode == 5) //Display Auton Name
		{
			clearLCD();
			displayLCDCenteredString(0,"Left Push");
			displayLCDCenteredString(1,"<<   Enter   >>");
		}
		else if (autonomousMode == 6) //Display Auton Name
		{
			clearLCD();
			displayLCDCenteredString(0,"Right Push");
			displayLCDCenteredString(1,"<<   Enter   >>");
		}
		else if (autonomousMode == 7) //Display Auton Name
		{
			clearLCD();
			displayLCDCenteredString(0,"Left Pole");
			displayLCDCenteredString(1,"<<   Enter   >>");
		}
		else if (autonomousMode == 8) //Display Auton Name
		{
			clearLCD();
			displayLCDCenteredString(0,"Right Pole");
			displayLCDCenteredString(1,"<<   Enter   >>");
		}
		else if (autonomousMode == 9) //Display Auton Name
		{
			clearLCD();
			displayLCDCenteredString(0,"Left 13");
			displayLCDCenteredString(1,"<<   Enter   >>");
		}
		else if (autonomousMode == 10) //Display Auton Name
		{
			clearLCD();
			displayLCDCenteredString(0,"Right 13");
			displayLCDCenteredString(1,"<<   Enter   >>");
		}
		else if (autonomousMode == 11) //Display Auton Name
		{
			clearLCD();
			displayLCDCenteredString(0,"Nothing");
			displayLCDCenteredString(1,"<<   Enter   >>");
		}
		if (autonomousMode < 1)
		{
			autonomousMode = 11;
		}
		else if (autonomousMode > 11)
		{
			autonomousMode = 1;
		}
		wait1Msec(10);
	}
	clearLCD();
	bLCDBacklight = false;
}



//--------------------------------------------// Pre_Auton
//--------------------------------------------// Pre_Auton
//--------------------------------------------// Pre_Auton

void pre_auton()
{
	resetSensors();
	clearLCD();

	bLCDBacklight = true;

	SensorType[Gyro] = sensorNone;
	displayLCDCenteredString(0, "Welcome to");
	displayLCDCenteredString(1, "Team 2011F");
	wait1Msec(1000);

	clearLCD();

	SensorType[Gyro] = sensorGyro;
	displayLCDCenteredString(0, "Ohio State");
	displayLCDCenteredString(1, "Champions");
	wait1Msec(1000);

	clearLCD();

	displayLCDCenteredString(0, "Two Skinky");
	displayLCDCenteredString(1, "Robot");
	wait1Msec(1000);

	autonomousSelection();
}



//--------------------------------------------// Autonomus
//--------------------------------------------// Autonomus
//--------------------------------------------// Autonomus

task autonomous()
{

	if (autonomousMode == 1) //Left Side 3 Cone 20 Point Zone
	{
		{
			resetSensors();
			motor[DR4B] = 110;
			motor[MG] = -127;
			driveForwards(127,50);
			motor[DR4B] = 10;
			wait1Msec(750);
			resetSensors();
			driveForwards(100,700);
			wait1Msec(50);
			resetSensors();
			motor[MG] = 0;
			driveForwards(127,265);
			wait1Msec(50);
			liftMobileGoal(115,1500); //Grab Mobile Goal
			motor[DR4B] = 0;
			wait1Msec(100);
			releaseCone(127,200); //Drop 1st Cone
			motor[DR4B] = 5;
			resetSensors();
			motor[MG] = 5;
			driveForwards(60,12);
			motor[DR4B] = -127;
			timeLowerChainBar(127,640);
			motor[CB] = -100;
			grabCone(127,250); //Grab 2nd Cone
			motor[Roller] = -50;
			motor[DR4B] = 28;
			timeLiftChainBar(127,770);
			motor[DR4B] = -20;
			releaseCone(127,200); //Drop 2nd Cone
			motor[DR4B] = 40;
			resetSensors();
			driveForwards(50,138);
			timeLiftDR4B(60,100);
			motor[DR4B] = -127;
			timeLowerChainBar(127,640);
			motor[CB] = -100;
			grabCone(127,250); //Grab 3rd Cone
			motor[Roller] = -50;
			motor[DR4B] = 60;
			timeLiftChainBar(127,800);
			motor[DR4B] = -30;
			resetSensors();
			driveBackwards(100,1100); //Back to Point Zone
			resetSensors();
			motor[Roller] = 50;
			driveBackwards(100,300);
			motor[Roller] = 12;
			resetSensors();
			turnRight(100,120);
			resetSensors();
			driveForwards(100,250); //Across the Point Zone
			motor[DR4B] = 40;
			resetSensors();
			turnRight(100,40);
			resetSensors();
			driveBackwards(80,80);
			motor[DR4B] = 0;
			resetSensors();
			motor[MG] = 0;
			driveForwards(127,400); //Drive over the Bar
			resetSensors();
			motor[MG] = -127;
			motor[DR4B] = 100;
			driveForwards(127,500); //Put Mobile Goal in 20
			wait1Msec(300);
			resetSensors();
			motor[DR4B] = 0;
			driveBackwards(127,500);
			motor[MG] = 0;
		}
	}

	//-------------------------------------------------------------------------//

	else if (autonomousMode == 2) //Right Side 3 Cone 20 Point Zone
	{
		{
			resetSensors();
			motor[DR4B] = 110;
			motor[MG] = -127;
			driveForwards(127,50);
			motor[DR4B] = 10;
			wait1Msec(750);
			resetSensors();
			driveForwards(100,700);
			wait1Msec(50);
			resetSensors();
			motor[MG] = 0;
			driveForwards(127,265);
			wait1Msec(50);
			liftMobileGoal(115,1500); //Grab Mobile Goal
			motor[DR4B] = 0;
			wait1Msec(100);
			releaseCone(127,200); //Drop 1st Cone
			motor[DR4B] = 5;
			resetSensors();
			motor[MG] = 5;
			driveForwards(60,12);
			motor[DR4B] = -127;
			timeLowerChainBar(127,640);
			motor[CB] = -100;
			grabCone(127,250); //Grab 2nd Cone
			motor[Roller] = -50;
			motor[DR4B] = 28;
			timeLiftChainBar(127,770);
			motor[DR4B] = -20;
			releaseCone(127,200); //Drop 2nd Cone
			motor[DR4B] = 40;
			resetSensors();
			driveForwards(50,138);
			timeLiftDR4B(60,100);
			motor[DR4B] = -127;
			timeLowerChainBar(127,640);
			motor[CB] = -100;
			grabCone(127,250); //Grab 3rd Cone
			motor[Roller] = -50;
			motor[DR4B] = 60;
			timeLiftChainBar(127,800);
			motor[DR4B] = -30;
			resetSensors();
			driveBackwards(100,1100); //Back to Point Zone
			resetSensors();
			motor[Roller] = 50;
			driveBackwards(100,300);
			motor[Roller] = 12;
			resetSensors();
			turnLeft(100,120);
			resetSensors();
			driveForwards(100,250); //Across the Point Zone
			motor[DR4B] = 40;
			resetSensors();
			turnLeft(100,40);
			resetSensors();
			driveBackwards(80,80);
			motor[DR4B] = 0;
			resetSensors();
			motor[MG] = 0;
			driveForwards(127,400); //Drive over the Bar
			resetSensors();
			motor[MG] = -127;
			motor[DR4B] = 100;
			driveForwards(127,500); //Put Mobile Goal in 20
			wait1Msec(300);
			resetSensors();
			motor[DR4B] = 0;
			driveBackwards(127,500);
			motor[MG] = 0;
		}
	}

	//-------------------------------------------------------------------------//

	else if (autonomousMode == 3) //Left Side 4 Cone 10 Point Zone
	{
		{
			resetSensors();
			motor[DR4B] = 110;
			motor[MG] = -127;
			driveForwards(127,50);
			motor[DR4B] = 10;
			wait1Msec(750);
			resetSensors();
			driveForwards(100,700);
			wait1Msec(50);
			resetSensors();
			motor[MG] = 0;
			driveForwards(127,265);
			wait1Msec(50);
			liftMobileGoal(115,1500); //Grab Mobile Goal
			motor[DR4B] = 0;
			wait1Msec(100);
			releaseCone(127,200); //Drop 1st Cone
			motor[DR4B] = 5;
			resetSensors();
			motor[MG] = 5;
			driveForwards(60,12);
			motor[DR4B] = -127;
			timeLowerChainBar(127,640);
			motor[CB] = -100;
			grabCone(127,250); //Grab 2nd Cone
			motor[Roller] = -50;
			motor[DR4B] = 28;
			timeLiftChainBar(127,770);
			motor[DR4B] = -20;
			releaseCone(127,200); //Drop 2nd Cone
			motor[DR4B] = 40;
			resetSensors();
			driveForwards(50,138);
			timeLiftDR4B(60,100);
			motor[DR4B] = -127;
			timeLowerChainBar(127,640);
			motor[CB] = -100;
			grabCone(127,250); //Grab 3rd Cone
			motor[Roller] = -50;
			motor[DR4B] = 28;
			timeLiftChainBar(127,770);
			releaseCone(127,200); //Drop 3rd Cone
			motor[DR4B] = 40;
			resetSensors();
			driveForwards(50,100);
			timeLiftDR4B(60,100);
			motor[DR4B] = -127;
			timeLowerChainBar(127,640);
			motor[Roller] = -50;
			motor[DR4B] = 60;
			timeLiftChainBar(127,800);
			motor[CB] = -100;
			grabCone(127,250); //Grab 4th Cone
			motor[Roller] = -50;
			motor[DR4B] = 28;
			timeLiftChainBar(127,770);
			releaseCone(127,200); //Drop 4th Cone
			resetSensors();
			driveBackwards(100,1350); //Back to Point Zone
			motor[DR4B] = 40;
			motor[Roller] = 20;
			resetSensors();
			turnRight(100,163); //Turn to Point Zone
			resetSensors();
			driveForwards(100,150);
			lowerMobileGoal(127,1400); //Put MG in 10
			motor[DR4B] = 0;
			motor[Roller] = 0;
			resetSensors();
			driveBackwards(127,500);
		}
	}

	//-------------------------------------------------------------------------//

	else if (autonomousMode == 4) //Right Side 4 Cone 10 Point Zone
	{
		{
			resetSensors();
			motor[DR4B] = 110;
			motor[MG] = -127;
			driveForwards(127,50);
			motor[DR4B] = 10;
			wait1Msec(750);
			resetSensors();
			driveForwards(100,700);
			wait1Msec(50);
			resetSensors();
			motor[MG] = 0;
			driveForwards(127,265);
			wait1Msec(50);
			liftMobileGoal(115,1500); //Grab Mobile Goal
			motor[DR4B] = 0;
			wait1Msec(100);
			releaseCone(127,200); //Drop 1st Cone
			motor[DR4B] = 5;
			resetSensors();
			motor[MG] = 5;
			driveForwards(60,12);
			motor[DR4B] = -127;
			timeLowerChainBar(127,640);
			motor[CB] = -100;
			grabCone(127,250); //Grab 2nd Cone
			motor[Roller] = -50;
			motor[DR4B] = 28;
			timeLiftChainBar(127,770);
			motor[DR4B] = -20;
			releaseCone(127,200); //Drop 2nd Cone
			motor[DR4B] = 40;
			resetSensors();
			driveForwards(50,138);
			timeLiftDR4B(60,100);
			motor[DR4B] = -127;
			timeLowerChainBar(127,640);
			motor[CB] = -100;
			grabCone(127,250); //Grab 3rd Cone
			motor[Roller] = -50;
			motor[DR4B] = 28;
			timeLiftChainBar(127,770);
			releaseCone(127,200); //Drop 3rd Cone
			motor[DR4B] = 40;
			resetSensors();
			driveForwards(50,100);
			timeLiftDR4B(60,100);
			motor[DR4B] = -127;
			timeLowerChainBar(127,640);
			motor[Roller] = -50;
			motor[DR4B] = 60;
			timeLiftChainBar(127,800);
			motor[CB] = -100;
			grabCone(127,250); //Grab 4th Cone
			motor[Roller] = -50;
			motor[DR4B] = 28;
			timeLiftChainBar(127,770);
			releaseCone(127,200); //Drop 4th Cone
			resetSensors();
			driveBackwards(100,1350); //Back to Point Zone
			motor[DR4B] = 40;
			motor[Roller] = 20;
			resetSensors();
			turnLeft(100,163); //Turn to Point Zone
			resetSensors();
			driveForwards(100,150);
			lowerMobileGoal(127,1400); //Put MG in 10
			motor[DR4B] = 0;
			motor[Roller] = 0;
			resetSensors();
			driveBackwards(127,500);
		}
	}

	//-------------------------------------------------------------------------//

	else if (autonomousMode == 5) //Left Side Middle 12 Point: Push Cones, Grab Mobile Goal, Place in 10 with One Cone
	{
		{
			//Put Code Here
		}
	}

	//-------------------------------------------------------------------------//

	else if (autonomousMode == 6) //Right Side Middle 12 Point: Push Cones, Grab Mobile Goal, Place in 10 with One Cone
	{
		{
			resetSensors();
			driveForwards(127,300);
			wait1Msec(100);
			resetSensors();
			turnRight(100,27);
			wait1Msec(100);
			resetSensors();
			driveForwards(100,250);
			wait1Msec(100);
			resetSensors();
			turnLeft(100,28.5);
			wait1Msec(100);
			resetSensors();
			driveForwards(127,1700); //Push Cones
			wait1Msec(100);
			resetSensors();
			driveBackwards(100,200);
			motor[MG] = -127;
			resetSensors();
			driveBackwards(100,920);
			resetSensors();
			turnLeft(70,4);
			motor[MG] = -50;
			wait1Msec(600);
			resetSensors();
			motor[MG] = 0;
			driveForwards(100,300);
			timeLiftDR4B(100,250);
			liftMobileGoal(127,1700); //Pick up MG
			resetSensors();
			turnLeft(100,30);
			resetSensors();
			driveBackwards(100,230);
			resetSensors();
			turnLeft(100,65);
			motor[Roller] = 127; //Drop cone
			resetSensors();
			driveForwards(127,800);
			resetSensors();
			turnLeft(100,8);
			resetSensors();
			motor[MG] = -127;
			driveForwards(127,120); //Drop MG in 10 pt zone
			resetSensors();
			wait1Msec(1000);
			driveBackwards(100,200);
		}
	}

	//-------------------------------------------------------------------------//

	else if (autonomousMode == 7) //Left Side 3 Cone Stationary Pole
	{
		{
			//Put Code Here
		}
	}

	//-------------------------------------------------------------------------//

	else if (autonomousMode == 8) //Right Side 3 Cone Stationary Pole
	{
		{
			//Put Code Here
		}
	}

	//-------------------------------------------------------------------------//

	else if (autonomousMode == 9) //Left Side 4 Cone 5 Point Zone
	{
		{
			//Put Code Here
		}
	}

	//-------------------------------------------------------------------------//

	else if (autonomousMode == 10) //Right Side 4 Cone 5 Point Zone
	{
		{
			//Put Code Here
		}
	}

	//-------------------------------------------------------------------------//

	else if (autonomousMode == 11) //Nothing Auton
	{
		{
			//Put Code Here
		}
	}

	//-------------------------------------------------------------------------//

	clearLCD();
	bLCDBacklight = false;
}



//--------------------------------------------// Usercontrol
//--------------------------------------------// Usercontrol
//--------------------------------------------// Usercontrol

task usercontrol()
{
	while (true)
	{

		//--------------------------------------------// Chain Bar

		if (vexRT[Btn7U] == 1)
		{
			motor[CB] = 127;
		}
		else if (vexRT[Btn7D] == 1)
		{
			motor[CB] = -127;
		}
		else
		{
			motor[CB] = 0;
		}

		//--------------------------------------------//


		//--------------------------------------------// Cone Intake

		if(vexRT[Btn6U] == 1)
		{
			motor[Roller] = -127;
		}
		else if(vexRT[Btn6D] == 1)
		{
			motor[Roller] = 127;
		}
		else
		{
			motor[Roller] = -15;
		}

		//--------------------------------------------//


		//--------------------------------------------// DR4B

		if (vexRT[Btn5U] == 1)
		{
			motor[DR4B] = 127;
		}
		else if (vexRT[Btn5D] == 1)
		{
			motor[DR4B] = -127;
		}
		else
		{
			motor[DR4B] = 0;
		}

		//--------------------------------------------//


		//--------------------------------------------// Mobile Goal

		if (vexRT[Btn8U] == 1)
		{
			motor[MG] = 127;
		}
		else if (vexRT[Btn8D] == 1)
		{
			motor[MG] = -127;
		}
		else
		{
			motor[MG] = 0;
		}

		//--------------------------------------------//


		//--------------------------------------------// Drive

		motor[RD1] = vexRT[Ch2];
		motor[RD2] = vexRT[Ch2];
		motor[LD1] = vexRT[Ch3];
		motor[LD2] = vexRT[Ch3];

		//--------------------------------------------//

	}
}
